const userSchema = [
  {
    email: "maga1@aa.aa",
    username: "maga",
    password: "1234",
    admin: true,
    id: "maga1@aa.a",
    playList: [],
    createdAt: "2024.06.05.1",
    likedMusic: [],
    recentMusic: [],
  },
  {
    email: "maga2@aa.aa",
    username: "maga1",
    password: "1234",
    admin: true,
    id: "maga2@aa.a",
    playList: [],
    createdAt: "2024.06.05.2",
    likedMusic: [],
    recentMusic: [],
  },
  {
    email: "maga3@aa.aa",
    username: "maga1",
    password: "1234",
    admin: true,
    id: "maga3@aa.a",
    playList: [],
    createdAt: "2024.06.05.3",
    likedMusic: [],
    recentMusic: [],
  },
];
